name: Linux Build
on: [push,pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: build
        run: |
             cmake ./
             make -j4
