name: Windows Build
on: [push,pull_request]

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Installing vcpkg (windows)
        run: |
          cd ..
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          git checkout
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install cppzmq:x64-windows
      - name: build
        run: |
             cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build
             cmake --build ${{ github.workspace }}/build --config Release
