name: Windows Build
on: [push,pull_request]

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Installing vcpkg (windows)
        run: |
          cd ..
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          git checkout
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install cppzmq:x64-windows
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3
        with:
            vs-prerelease: true
      - name: build
        run: |
             cd ${{ github.workspace }}
             cmake ./
      - name: Build Solution (windows)
        run: |
          msbuild quneiform.sln
